### ISSUE TITLE
ChatBOX

### ISSUE THREAD

**Issue by ajpar** [sylveryte/pokemonMayhem#3]
look in this matter.....

**Comment by sylveryte** [comment]
It's feature, they in grass :dancer:

**Comment by ajpar** [comment]
:-1:

**Comment by sylveryte** [comment]
:facepunch:

**Comment by ajpar** [comment]
:facepunch: :angry: :bomb:

**Comment by sylveryte** [comment]
:gun:

**Comment by sylveryte** [comment]
:laughing:

**Comment by ajpar** [comment]
:sandal:

**Comment by ajpar** [comment]
:hammer:

**Comment by sylveryte** [comment]
aaeee!! ladki :girl:

**Comment by sylveryte** [comment]
:mailbox_closed: marr jaaa

**Comment by sylveryte** [comment]
this is me :rabbit:

**Comment by ajpar** [comment]
:warning: jada mat bol

**Comment by sylveryte** [comment]
:open_hands:

**Comment by ajpar** [comment]
{ :facepunch:

**Comment by sylveryte** [comment]
:ox:

**Comment by sylveryte** [comment]
hahhahahhahahahhahahhahahhahahah :laughing:

**Comment by sylveryte** [comment]
:innocent:

**Comment by ajpar** [comment]
:fu:

**Comment by ajpar** [comment]
ha ha ha h

**Comment by sylveryte** [comment]
:ox:
:ox:
:ox:
:ox:

**Comment by ajpar** [comment]
never

**Comment by ajpar** [comment]
:foggy:

**Comment by sylveryte** [comment]
:ox:
:ox:
:ox:
:ox:


:ox:
:ox:
:ox:
:ox:


:ox:
:ox:
:ox:
:ox:

**Comment by sylveryte** [comment]
:ox:
:ox:
:ox:
:ox:

:ox:
:ox:
:ox:
:ox:

:ox:
:ox:
:ox:
:ox:


:ox:
:ox:
:ox:
:ox:

:ox:
:ox:
:ox:
:ox:

:ox:
:ox:
:ox:
:ox:



:ox:
:ox:
:ox:
:ox:

:ox:
:ox:
:ox:
:ox:

:ox:
:ox:
:ox:
:ox:



:ox:
:ox:
:ox:
:ox:

:ox:
:ox:
:ox:
:ox:

:ox:
:ox:
:ox:
:

:ox:
:ox:
:ox:
:ox:

:ox:
:ox:
:ox:
:ox:

:ox:
:ox:
:ox:
:ox:




:ox:
:ox:
:ox:
:ox:

:ox:
:ox:
:ox:
:ox:

:ox:
:ox:
:ox:
:ox:



:ox:
:ox:
:ox:
:ox:

:ox:
:ox:
:ox:
:ox:

:ox:
:ox:
:ox:
:ox:



:ox:
:ox:
:ox:
:ox:

:ox:
:ox:
:ox:
:ox:

:ox:
:ox:
:ox:
:ox:


:ox:
:ox:
:ox:
:ox:

:ox:
:ox:
:ox:
:ox:

:ox:
:ox:
:ox:
:ox:
